---
on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        compiler: [GCC, CLANG, CLANG-CL-MSVC]
        mbedtlsversion: ["v3.6.0", "mbedtls-3.6.1"]
    container: ghcr.io/philips-software/amp-devcontainer-cpp:5.6.0@sha256:884732270a353e8446f813e649f2918ac53ce446a6c0dd4f7f84a6d58fb26bce
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        id: cache-winsdk
        with:
          path: /winsdk
          key: cache-winsdk

      - if: ${{ steps.cache-winsdk.outputs.cache-hit != 'true' }}
        run: xwin --accept-license --manifest-version 17 splat --preserve-ms-arch-notation --include-debug-libs && mv .xwin-cache/splat/ /winsdk

      - uses: lukka/run-cmake@af1be47fd7c933593f687731bc6fdbee024d3ff4 # v10.8
        with:
          configurePreset: ${{ matrix.compiler }}
          buildPreset: ${{ matrix.compiler }}
          configurePresetAdditionalArgs: "['-DCUSTOM_MBEDTLS_VERSION=${{ matrix.mbedtlsversion }}']"
